"""baseline: schema initial JMH Orbit

Revision ID: 9be1d41da284
Revises: 
Create Date: 2026-10-05 11:53:15.379196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be1d41da284'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cle', sa.String(length=120), nullable=False),
    sa.Column('valeur', sa.Text(), nullable=True),
    sa.Column('type_valeur', sa.String(length=20), nullable=True),
    sa.Column('service', sa.String(length=50), nullable=True),
    sa.Column('masque', sa.Boolean(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_cle'), ['cle'], unique=True)

    op.create_table('equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('couleur', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('equipe_email', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('prenom', sa.String(length=80), nullable=False),
    sa.Column('photo_profil', sa.String(length=200), nullable=True),
    sa.Column('photo_data', sa.LargeBinary(), nullable=True),
    sa.Column('photo_mimetype', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('pole', sa.String(length=20), nullable=True),
    sa.Column('equipe_id', sa.Integer(), nullable=True),
    sa.Column('poste', sa.String(length=120), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_arrivee', sa.Date(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_dossier', sa.String(length=50), nullable=False),
    sa.Column('intitule', sa.String(length=200), nullable=False),
    sa.Column('collaborateur_id', sa.Integer(), nullable=True),
    sa.Column('regime_tva', sa.String(length=50), nullable=True),
    sa.Column('date_limite_declaration', sa.Date(), nullable=True),
    sa.Column('date_acompte_1', sa.Date(), nullable=True),
    sa.Column('date_acompte_2', sa.Date(), nullable=True),
    sa.Column('pennylane_customer_id', sa.String(length=64), nullable=True),
    sa.Column('pennylane_api_token', sa.String(length=256), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_cloture', sa.DateTime(), nullable=True),
    sa.Column('frequence_tva', sa.String(length=20), nullable=True),
    sa.Column('regime_fiscale', sa.String(length=10), nullable=True),
    sa.Column('has_cfe', sa.Boolean(), nullable=True),
    sa.Column('forme_juridique', sa.String(length=20), nullable=True),
    sa.Column('secteur_activite', sa.String(length=60), nullable=True),
    sa.Column('siren', sa.String(length=9), nullable=True),
    sa.Column('honoraires_mensuel', sa.Float(), nullable=True),
    sa.Column('collaborateur_social_id', sa.Integer(), nullable=True),
    sa.Column('tva_intra', sa.String(length=20), nullable=True),
    sa.Column('naf_code', sa.String(length=10), nullable=True),
    sa.Column('effectif_label', sa.String(length=40), nullable=True),
    sa.Column('categorie_entreprise', sa.String(length=5), nullable=True),
    sa.Column('date_creation_entreprise', sa.Date(), nullable=True),
    sa.Column('dirigeant', sa.String(length=200), nullable=True),
    sa.Column('adresse_siege', sa.String(length=250), nullable=True),
    sa.Column('etat_administratif', sa.String(length=5), nullable=True),
    sa.Column('enrichi_le', sa.DateTime(), nullable=True),
    sa.Column('equipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collaborateur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collaborateur_social_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dossiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossiers_numero_dossier'), ['numero_dossier'], unique=True)
        batch_op.create_index(batch_op.f('ix_dossiers_siren'), ['siren'], unique=False)

    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('periode', sa.String(length=20), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('dossiers_termines', sa.Integer(), nullable=True),
    sa.Column('taches_terminees', sa.Integer(), nullable=True),
    sa.Column('taches_en_retard', sa.Integer(), nullable=True),
    sa.Column('taux_respect_delai', sa.Float(), nullable=True),
    sa.Column('score_performance', sa.Float(), nullable=True),
    sa.Column('date_calcul', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('taxe', sa.String(length=20), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('declare', sa.Boolean(), nullable=True),
    sa.Column('paye', sa.Boolean(), nullable=True),
    sa.Column('pl_mode', sa.Boolean(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('date_modif', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'taxe', 'annee', 'mois', 'kind', name='uq_checklist_entry')
    )
    with op.batch_alter_table('checklist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_entries_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('dsn_suivi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('dsn_statut', sa.String(length=20), nullable=True),
    sa.Column('dsn_date_depot', sa.Date(), nullable=True),
    sa.Column('dsn_motif', sa.String(length=250), nullable=True),
    sa.Column('ecritures_statut', sa.String(length=20), nullable=True),
    sa.Column('ecritures_date', sa.DateTime(), nullable=True),
    sa.Column('notifie_compta', sa.Boolean(), nullable=True),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('date_modif', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'annee', 'mois', name='uq_dsn_suivi')
    )
    with op.batch_alter_table('dsn_suivi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dsn_suivi_annee'), ['annee'], unique=False)
        batch_op.create_index(batch_op.f('ix_dsn_suivi_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('pennylane_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('date_item', sa.String(length=30), nullable=True),
    sa.Column('vu_premiere_fois', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('api_statut', sa.String(length=30), nullable=True),
    sa.Column('statut_par_id', sa.Integer(), nullable=True),
    sa.Column('statut_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['statut_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'item_type', 'item_id', name='uq_pl_item')
    )
    with op.batch_alter_table('pennylane_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pennylane_items_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pennylane_items_item_id'), ['item_id'], unique=False)

    op.create_table('suggestions_taches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sujet', sa.String(length=200), nullable=False),
    sa.Column('corps', sa.Text(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('titre_suggere', sa.String(length=200), nullable=False),
    sa.Column('description_suggeree', sa.Text(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('cree_par', sa.Integer(), nullable=True),
    sa.Column('valide_par', sa.Integer(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('mail_uid', sa.String(length=64), nullable=True),
    sa.Column('priorite_suggeree', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['valide_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail_uid')
    )
    op.create_table('taches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('assigne_a', sa.Integer(), nullable=True),
    sa.Column('cree_par', sa.Integer(), nullable=True),
    sa.Column('priorite', sa.String(length=20), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('date_echeance', sa.Date(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_prise_en_charge', sa.DateTime(), nullable=True),
    sa.Column('date_completion', sa.DateTime(), nullable=True),
    sa.Column('frequence_repetition', sa.String(length=20), nullable=True),
    sa.Column('fin_repetition', sa.Date(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigne_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cree_par'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['taches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tva_statuts_pennylane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('deadline', sa.String(length=20), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('date_sync', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'annee', 'mois', name='uq_tva_statut_pl')
    )
    with op.batch_alter_table('tva_statuts_pennylane', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tva_statuts_pennylane_annee'), ['annee'], unique=False)
        batch_op.create_index(batch_op.f('ix_tva_statuts_pennylane_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('commentaires_taches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tache_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tache_id'], ['taches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tache_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=True),
    sa.Column('type_notification', sa.String(length=30), nullable=True),
    sa.Column('date_envoi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tache_id'], ['taches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('commentaires_taches')
    with op.batch_alter_table('tva_statuts_pennylane', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tva_statuts_pennylane_dossier_id'))
        batch_op.drop_index(batch_op.f('ix_tva_statuts_pennylane_annee'))

    op.drop_table('tva_statuts_pennylane')
    op.drop_table('taches')
    op.drop_table('suggestions_taches')
    with op.batch_alter_table('pennylane_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pennylane_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_pennylane_items_dossier_id'))

    op.drop_table('pennylane_items')
    with op.batch_alter_table('dsn_suivi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dsn_suivi_dossier_id'))
        batch_op.drop_index(batch_op.f('ix_dsn_suivi_annee'))

    op.drop_table('dsn_suivi')
    with op.batch_alter_table('checklist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_entries_dossier_id'))

    op.drop_table('checklist_entries')
    op.drop_table('performance')
    with op.batch_alter_table('dossiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossiers_siren'))
        batch_op.drop_index(batch_op.f('ix_dossiers_numero_dossier'))

    op.drop_table('dossiers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('equipes')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_cle'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
